name: Test flow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test run

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: lasseebert/depseus@main
        name: Depseus
        id: depseus
        with:
          assignee: 'lasseebert'

      - name: Get the output
        run: 'echo "Was issue created: ${{ steps.depseus.outputs.created }}"'
